######服务器参数############
server:
  port: 9000
  servlet:
    session:
      timeout: 1800
    context-path: /
        
  tomcat:
    uri-encoding: UTF-8
spring:
    datasource:
        name: wxmp
        url: jdbc:mysql://172.18.235.107:3306/db_wxmp
        username: jee
        password: YesOrNoAnd0+1
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.jeekhan.wxmp.model
 
logging:
  level:
    com.jeekhan.wx.mapper: DEBUG
######微信参数############
wx:
#userId 公众号
  PUBLIC-USER-ID: gh_ed70fd57008b
#appId
  APPID: wx8864bd7398aa5270
#appSecret
  APPSECRET: c2c15a91c950e8a6fc106192b044adfb
#token
  TOKEN: 1314
  
######业务参数############
#用户注册URL、注销URL
busi:
  user-create-url: 'http://172.18.235.107:8080/user/create'
  user-cancel-url: 'http://172.18.235.107:8080/user/cancel'
  
######系统参数############  
sys:
  tmp-file-dir: '/tmp/wxmp/'
  qrcode-file-dir: '/var/wxmp/qrcode/'
  material-file-dir: '/var/wxmp/material/'
  kf-headimg-dir: '/var/wxmp/headimg/'
  wxmenu-file-dir: '/var/wxmp/wxmenu/'
  