######服务器参数############
server:
  port: 9000
  servlet:
    session:
      timeout: 1800
    context-path: /wxmp
        
  tomcat:
    uri-encoding: UTF-8
spring:
    datasource:
        name: wxmp
        url: jdbc:mysql://192.168.0.104:3306/wxmp
        username: jee
        password: jee8901
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.jeekhan.wxmp.model
 
logging:
  level:
    com.jeekhan.wx.mapper: DEBUG
######微信参数############
wx:
#userId 公众号
  PUBLIC-USER-ID: gh_ed70fd57008b
#appId
  APPID: wx8864bd7398aa5270
#appSecret
  APPSECRET: c2c15a91c950e8a6fc106192b044adfb
#token
  TOKEN: 1314
#自定义菜单
  DEFAULT-MENU: '{"button":[{"name": "扫码", "sub_button": [{"type": "scancode_waitmsg", "name": "扫码带提示", "key": "rselfmenu_0_0"}, { "type": "scancode_push", "name": "扫码推事件",  "key": "rselfmenu_0_1"}]}, {"name": "发图", "sub_button": [{"type": "pic_sysphoto", "name": "系统拍照发图", "key": "rselfmenu_1_0"}, {"type": "pic_photo_or_album", "name": "拍照或者相册发图","key": "rselfmenu_1_1"}, {"type": "pic_weixin", "name": "微信相册发图", "key": "rselfmenu_1_2"}]}, {"name": "其他", "sub_button": [{"name": "发送位置", "type": "location_select", "key": "rselfmenu_2_0"},{"name": "点击", "type": "click", "key": "CLICK-KEY-1"}, { "name": "链接-搜索", "type": "view",  "url":"http://www.soso.com/"}]}]}'

  
######业务参数############
#用户注册URL、注销URL
busi:
  user-create-url: 'http://localhost:8080/mfyx/user-create'
  user-cancel-url: 'http://localhost:8080/mfyx/user-cancel'
  
######系统参数############  
sys:
  tmp-file-dir: '/Users/jeekhan/wxmp/tmp/'
  qrcode-file-dir: '/Users/jeekhan/wxmp/qrcode/'
  material-file-dir: '/Users/jeekhan/wxmp/material/'
  kf-headimg-dir: '/Users/jeekhan/wxmp/headimg/'
  wxmenu-file-dir: '/Users/jeekhan/wxmp/wxmenu/'
  